# Generated by Django 5.0.6 on 2024-07-07 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gameCarecters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('type', models.CharField(choices=[('Free', 'Free'), ('Premium', 'Premium')], max_length=30)),
                ('photo', models.FileField(upload_to='C:\\Users\\abdo7\\OneDrive\\Bureau\\hollow-4\\venv\\crud\\static/images/upload')),
            ],
        ),
        migrations.CreateModel(
            name='power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.FileField(upload_to='C:\\Users\\abdo7\\OneDrive\\Bureau\\hollow-4\\venv\\crud\\static/images/upload')),
            ],
        ),
    ]
