# Generated by Django 5.0.6 on 2024-07-07 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='power',
            name='gameCarecter',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='crudApp.gamecarecters'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='power',
            name='photo',
            field=models.FileField(null=True, upload_to='C:\\Users\\abdo7\\OneDrive\\Bureau\\hollow-4\\venv\\crud\\static/images/upload'),
        ),
    ]
