# Generated by Django 5.0.6 on 2024-07-07 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crudApp', '0005_remove_power_gamecarecter_gamecarecters_power'),
    ]

    operations = [
        migrations.RenameField(
            model_name='power',
            old_name='description',
            new_name='description_power',
        ),
        migrations.RenameField(
            model_name='power',
            old_name='name',
            new_name='name_power',
        ),
    ]
